config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :books
  resources :book_cards
  resources :book_issues
  resources :book_returns
  resources :libraries
  resources :readers
  resources :types
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base # rubocop:disable Style/Documentation
  primary_abstract_class
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord # rubocop:disable Style/Documentation
  has_many :book_types
  has_many :types, through: :book_types
end

app/models/book_card.rb
# frozen_string_literal: true

class BookCard < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :book
  belongs_to :library
  belongs_to :reader

  has_one :book_issue, dependent: :destroy
end

app/models/book_issue.rb
# frozen_string_literal: true

class BookIssue < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :book_card

  has_one :book_return, dependent: :destroy, required: false

  validates :return_date, presence: true
  validate :return_date_within_valid_range

  after_create :create_book_return

  scope :not_returned_books, -> { where('return_date >= ?', Date.current) }

  private

  def return_date_within_valid_range
    return unless return_date.present? && return_date < Date.current + 1.week

    errors.add(:return_date, 'must be at least one week from the current date')
  end

  def create_book_return
    BookReturn.create!(book_issue: self, returned: false)
  end
end

app/models/book_return.rb
# frozen_string_literal: true

class BookReturn < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :book_issue

  scope :pending_returns, -> { where(returned: false) }
end

app/models/book_type.rb
# frozen_string_literal: true

class BookType < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :book
  belongs_to :type
end

app/models/library.rb
# frozen_string_literal: true

class Library < ApplicationRecord # rubocop:disable Style/Documentation
  has_many :library_memberships, dependent: :destroy
  has_many :readers, through: :library_memberships
  has_many :book_cards, dependent: :destroy
end

app/models/library_membership.rb
# frozen_string_literal: true

class LibraryMembership < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :library
  belongs_to :reader
end

app/models/reader.rb
# frozen_string_literal: true

class Reader < ApplicationRecord # rubocop:disable Style/Documentation
  has_many :library_memberships, dependent: :destroy
  has_many :libraries, through: :library_memberships
  has_many :book_cards, dependent: :destroy
end

app/models/type.rb
# frozen_string_literal: true

class Type < ApplicationRecord # rubocop:disable Style/Documentation
  has_many :book_types
  has_many :books, through: :book_types
end

app/controllers/book_issues_controller.rb
# frozen_string_literal: true

class BookIssuesController < ApplicationController # rubocop:disable Style/Documentation
  def index
    @book_issues = BookIssue.all
    @book_not_returns = BookIssue.not_returned_books
  end

  def new
    @book_issue = BookIssue.new(issue_date: Date.current)
  end

  def create
    @book_issue = BookIssue.new(book_issue_params.merge(issue_date: Date.current))

    if @book_issue.save
      redirect_to book_issues_path
    else
      render :new
    end
  end

  def destroy
    @book_issue = BookIssue.find(params[:id])
    redirect_to book_issues_path if @book_issue.destroy
  end

  private

  def book_issue_params
    params.require(:book_issue).permit(:return_date, :book_card_id)
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController # rubocop:disable Style/Documentation
  before_action :find_book, only: %i[show]

  def index
    @books = Book.all
  end

  def show; end

  private

  def book_params
    params.require(:book).permit(:title, :author_id, :book_type_id)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController # rubocop:disable Style/Documentation
  def index; end
end

app/controllers/types_controller.rb
# frozen_string_literal: true

class TypesController < ApplicationController # rubocop:disable Style/Documentation
  def index
    @types = Type.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # rubocop:disable Style/Documentation
end

app/helpers/book_cards_helper.rb
# frozen_string_literal: true

module BookCardsHelper # rubocop:disable Style/Documentation
end

app/helpers/book_issues_helper.rb
# frozen_string_literal: true

module BookIssuesHelper # rubocop:disable Style/Documentation
end

app/helpers/book_returns_helper.rb
# frozen_string_literal: true

module BookReturnsHelper # rubocop:disable Style/Documentation
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper # rubocop:disable Style/Documentation
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper # rubocop:disable Style/Documentation
end

app/helpers/libraries_helper.rb
# frozen_string_literal: true

module LibrariesHelper # rubocop:disable Style/Documentation
end

app/helpers/readers_helper.rb
# frozen_string_literal: true

module ReadersHelper # rubocop:disable Style/Documentation
end

app/helpers/types_helper.rb
# frozen_string_literal: true

module TypesHelper # rubocop:disable Style/Documentation
end

app/views/book_issues/_book_issue.html.erb
<tr>
  <td><%= book_issue.issue_date %></td>
  <td><%= book_issue.return_date %></td>
  <td><%= book_issue.book_card.uniq_number %></td>
  <td><%= link_to 'Delete', book_issue_path(book_issue), 
                            data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, 
                            class: 'btn btn-danger' %>
  </td>
</tr>

app/views/book_issues/index.html.erb
<h1 class="mt-5 mb-5">Таблица актуальных выдач книг:</h1>

<%= link_to "Создать новую выдачу книги", new_book_issue_path, class: 'btn btn-primary mb-3' %>

<% if @book_not_returns.empty? %>
  <h1 class="mt-5">Нет актуальных выдач!</h1>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Дата выдачи</th>
        <th scope="col">Дата возврата</th>
        <th scope="col">Книжная карточка</th>
        <th scope="col">Действия</th>
      </tr>
    </thead>
    <tbody>
      <%= render @book_not_returns %>
    </tbody>
  </table>
<% end %>  

 <%= link_to "Назад", books_path, class: "btn btn-primary mt-5" %>

app/views/book_issues/new.html.erb
<%= render 'shared/errors', object: @book_issue %>

<%= form_for @book_issue, data: { turbo: false } do |f| %>
  <div class="mb-3">
    <%= f.label :return_date, class: 'form-label' %>
    <%= f.date_field :return_date, class: 'form-control datepicker' %>
  </div>

  <div class="mb-3">
    <%= f.label :book_card_id, 'Book Card', class: 'form-label' %>
    <%= f.collection_select :book_card_id, BookCard.all, :id, :uniq_number, { prompt: 'Select a book card' }, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= f.submit 'Create Book Issue', class: 'btn btn-primary mt-3' %>
  </div>
<% end %>

<%= link_to 'Назад', book_issues_path, class: 'btn btn-primary mt-5' %>